{{ if $.Values.app.Service }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{ $.Values.app.group }}/app-name: {{ $.Values.app.name }}
    {{ $.Values.app.group }}/is-isolated-run: "false"
    {{- range $i, $label := $.Values.app.Service.Deployment.labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
  name: app-{{ $.Values.app.name }}
spec:
  type: ClusterIP
  ports:
{{ $.Values.app.Service.Process.servicePorts | toYaml | indent 4 }}
  selector:
    {{ $.Values.app.group }}/app-name: {{ $.Values.app.name }}
    {{ $.Values.app.group }}/app-process: {{ $.Values.app.Service.Process.name }}
    {{ $.Values.app.group }}/app-deployment-version: {{ $.Values.app.Service.Deployment.version | quote }}
    {{ $.Values.app.group }}/is-isolated-run: "false"
{{ end }}