{{- if .Values.app.isAccessible }}
{{- if .Values.app.ingress.https }}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.ingressController.className }}
    kubernetes.io/ingress.class: {{ .Values.ingressController.className }}
    {{- end }}
  labels:
    theketch.io/app-name: {{ $.Values.app.name }}
  name: {{ $.Values.app.name }}-https
spec:
  tls:
    {{- range $_, $https := .Values.app.ingress.https }}
    - hosts:
      - {{ $https.cname }}
      secretName: {{ $https.secretName }}
    {{- end }}
  rules:
    {{- range $_, $https := .Values.app.ingress.https }}
    - host: {{ $https.cname }}
      http:
        paths:
          {{- range $_, $deployment := $.Values.app.deployments }}
          {{- range $_, $process := $deployment.processes }}
          {{- if $process.routable }}
          - backend:
              serviceName: {{ printf "%s-%s-%v" $.Values.app.name $process.name $deployment.version }}
              servicePort: {{ $process.publicServicePort }}
          {{- end }}
          {{- end }}
          {{- end }}
    {{- end }}
---
{{- end }}

{{- if .Values.app.ingress.http }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.ingressController.className }}
    kubernetes.io/ingress.class: {{ .Values.ingressController.className }}
    {{- end }}
  labels:
    theketch.io/app-name: {{ $.Values.app.name }}
  name: {{ $.Values.app.name }}-http
spec:
  rules:
    {{- range $_, $cname := .Values.app.ingress.http }}
    - host: {{ $cname }}
      http:
        paths:
          {{- range $_, $deployment := $.Values.app.deployments }}
            {{- range $_, $process := $deployment.processes }}
            {{- if $process.routable }}
            - backend:
                serviceName: {{ printf "%s-%s-%v" $.Values.app.name $process.name $deployment.version }}
                servicePort: {{ $process.publicServicePort }}
            {{- end }}
            {{- end }}
            {{- end }}
    {{- end }}
  {{- end }}

{{- end }}
