# permissions for end users to edit traits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trait-editor-role
rules:
- apiGroups:
  - resources.theketch.io
  resources:
  - traits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.theketch.io
  resources:
  - traits/status
  verbs:
  - get
