{{ if eq $.Values.app.type "Deployment" }}
{{ range $_, $deployment := .Values.app.deployments }}
  {{ range $_, $process := $deployment.processes }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ $.Values.app.group }}/app-name: {{ $.Values.app.name | quote }}
    {{ $.Values.app.group }}/app-process: {{ $process.name | quote }}
    {{ $.Values.app.group }}/app-process-replicas: {{ $process.units | quote }}
    {{ $.Values.app.group }}/app-deployment-version: {{ $deployment.version | quote }}
    {{ $.Values.app.group }}/is-isolated-run: "false"
    app.kubernetes.io/name: {{ $.Values.app.name | quote }}
    app.kubernetes.io/instance: {{ $.Values.app.name | quote }}
    app.kubernetes.io/version: {{ $deployment.version | quote }}
    app.kubernetes.io/managed-by: "LensApps"
    {{- range $k, $v := $process.deploymentMetadata.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end}}
  {{- if $process.deploymentMetadata.annotations }}
  annotations:
    {{- range $k, $v := $process.deploymentMetadata.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
  name: {{ $.Values.app.name }}-{{ $process.name }}-{{ $deployment.version }}
spec:
  replicas: {{ $process.units }}
  selector:
    matchLabels:
      app: {{ default $.Values.app.name $.Values.app.id | quote }}
      version: {{ $deployment.version | quote }}
      {{ $.Values.app.group }}/app-name: {{ $.Values.app.name | quote }}
      {{ $.Values.app.group }}/app-process: {{ $process.name | quote }}
      {{ $.Values.app.group }}/app-deployment-version: {{ $deployment.version | quote }}
      {{ $.Values.app.group }}/is-isolated-run: "false"
      app.kubernetes.io/name: {{ $.Values.app.name | quote }}
      app.kubernetes.io/instance: {{ $.Values.app.name | quote }}
      app.kubernetes.io/version: {{ $deployment.version | quote }}
      app.kubernetes.io/managed-by: "LensApps"
  template:
    metadata:
      labels:
        app: {{ default $.Values.app.name $.Values.app.id | quote }}
        version: {{ $deployment.version | quote }}
        {{ $.Values.app.group }}/app-name: {{ $.Values.app.name | quote }}
        {{ $.Values.app.group }}/app-process: {{ $process.name | quote }}
        {{ $.Values.app.group }}/app-deployment-version: {{ $deployment.version | quote }}
        {{ $.Values.app.group }}/is-isolated-run: "false"
        app.kubernetes.io/name: {{ $.Values.app.name | quote }}
        app.kubernetes.io/instance: {{ $.Values.app.name | quote }}
        app.kubernetes.io/version: {{ $deployment.version | quote }}
        app.kubernetes.io/managed-by: "LensApps"
        {{- range $k, $v := $process.podMetadata.labels }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      {{- if $process.podMetadata.annotations }}
      annotations:
        {{- range $k, $v := $process.podMetadata.annotations }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      {{- end }}
    {{- template "app.podTemplate" (dict "root" $.Values "deployment" $deployment "process" $process) }}
---
{{ end }}
{{ end }}
  {{- end }}
